"""regen_readme.py — generate the README "First audit results" section
from entries/*.yaml so the published table can never drift from the YAML
source of truth.

Why this exists: the 2026-06-11 Fable 5 audit caught README claiming
several Sahil skills were "helpful (Brier 0.05)" while their YAML files
said "harmful (Brier 0.45)". The README was hand-edited. Hand-editing
results when the source of truth lives in YAML is how audit-of-the-
auditor projects die. This script ensures it never happens again.

Usage:
    python3 scripts/regen_readme.py             # rewrite README.md in place
    python3 scripts/regen_readme.py --check     # exit 1 if README differs
    python3 scripts/regen_readme.py --dry-run   # print the new block to stdout
"""
from __future__ import annotations
import argparse
import sys
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parent.parent
ENTRIES = REPO / "entries"
README = REPO / "README.md"

START_MARK = "## First audit results"
END_MARK = "\n## "


def load_entries() -> list[dict]:
    entries = []
    for path in sorted(ENTRIES.glob("*.yaml")):
        if path.name.startswith("_"):
            continue
        with path.open() as f:
            e = yaml.safe_load(f)
        if not e or "verdict" not in e:
            continue
        e["__file"] = path.name
        entries.append(e)
    return entries


def group_by_verdict(entries: list[dict]) -> dict[str, list[dict]]:
    out = {"helpful": [], "neutral": [], "harmful": []}
    for e in entries:
        v = e.get("verdict", "neutral")
        if v in out:
            out[v].append(e)
    return out


def format_entry_inline(e: dict) -> str:
    name = e.get("name") or e.get("slug") or e["__file"]
    brier = e.get("brier_score", 0)
    base = e.get("brier_baseline", 0.25)
    return f"`{name}` ({brier:.2f} vs {base:.2f})"


def render_block(entries: list[dict]) -> str:
    total = len(entries)
    by = group_by_verdict(entries)
    n_h, n_n, n_b = len(by["helpful"]), len(by["neutral"]), len(by["harmful"])

    def join(es: list[dict], cap: int = 8) -> str:
        items = [format_entry_inline(e) for e in es[:cap]]
        if len(es) > cap:
            items.append(f"({len(es) - cap} more)")
        return " · ".join(items) if items else "_none_"

    audit_dates = [e.get("audited_at") for e in entries if e.get("audited_at")]
    latest = max(audit_dates) if audit_dates else "(no dated audits yet)"

    lines = [
        f"## First audit results (regenerated {latest})",
        "",
        f"_Auto-generated by `scripts/regen_readme.py` from `entries/*.yaml`. "
        f"Do not hand-edit — run the script after every `audit.py` invocation._",
        "",
        f"{total} entries audited: **{n_h} helpful · {n_n} neutral · {n_b} harmful** "
        f"against no-skill baseline on the frozen v1.0 eval set.",
        "",
        "| Verdict | Count | Skills |",
        "|---|---|---|",
        f"| **helpful** | {n_h} | {join(by['helpful'])} |",
        f"| **neutral** | {n_n} | {join(by['neutral'])} |",
        f"| **harmful** ⚠️ | {n_b} | {join(by['harmful'])} |",
        "",
        "**Metric note:** the `brier_score` field is not a probabilistic Brier "
        "score — it's a transformed-win-rate squared error against the perfect "
        "score of 1.0 (`mean((1 - task_score)^2)`). The metric name is preserved "
        "for backward compatibility but the honest description lives in "
        "[docs/brier-method.md](docs/brier-method.md). N=5 binary tasks per skill, "
        "single Haiku pass, frozen eval set — directional verdicts only until "
        "we move to k≥10 repetitions with bootstrap CI.",
        "",
    ]
    return "\n".join(lines)


def splice_into_readme(new_block: str) -> str:
    src = README.read_text()
    start = src.find(START_MARK)
    if start == -1:
        # No existing block — append before Roadmap or at end
        anchor = src.find("\n## Roadmap")
        if anchor == -1:
            return src + "\n\n---\n\n" + new_block
        return src[:anchor] + "\n" + new_block + src[anchor:]
    # Find the next H2 heading
    rest = src[start:]
    end_idx = rest.find(END_MARK, 1)
    if end_idx == -1:
        end_idx = len(rest)
    return src[:start] + new_block + rest[end_idx:]


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--check", action="store_true",
                   help="exit 1 if README differs from regenerated version")
    p.add_argument("--dry-run", action="store_true",
                   help="print the block to stdout instead of writing")
    args = p.parse_args()

    entries = load_entries()
    new_block = render_block(entries)

    if args.dry_run:
        print(new_block)
        return 0

    new_readme = splice_into_readme(new_block)
    if args.check:
        if README.read_text() != new_readme:
            print("README is out of date — run scripts/regen_readme.py", file=sys.stderr)
            return 1
        return 0

    README.write_text(new_readme)
    print(f"Wrote {README.name} with verdicts for {len(entries)} entries")
    return 0


if __name__ == "__main__":
    sys.exit(main())
